name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Node.js dependencies
        run: npm install --legacy-peer-deps

      - name: Build Vite assets
        run: npm run build

      - name: Create .env.testing file
        run: |
          cp .env.testing.ci .env.testing  # Copy the non-sensitive configuration
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env.testing  # Inject APP_KEY
          echo "DB_PASSWORD=root" >> .env.testing  # Hardcode DB_PASSWORD as root

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            mysqladmin ping --host=127.0.0.1 --user=root --password=root && echo "MySQL is up" && exit 0
            echo "Waiting for MySQL..."
            sleep 3
          done
          echo "MySQL did not start in time" && exit 1

      - name: Run migrations
        run: |
          php artisan migrate --env=testing

      - name: Run test suite
        run: |
          php artisan test

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: get_my_furniture_testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
